name: Unit Tests

on: [pull_request]

jobs:
  jest-and-cypress-components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
          cache: "npm"
      - name: Run Tests
        run: |
          npm install 
          npm test
